# Build environment
dist: bionic

# Small image
language: minimal

# Download and unpack the stack executable
before_install:
- ( mkdir -p ~/.ghcup/bin && curl https://gitlab.haskell.org/haskell/ghcup/raw/master/ghcup > ~/.ghcup/bin/ghcup && chmod +x ~/.ghcup/bin/ghcup) && echo "Installed ghcup"
- export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
- ghcup -c install-cabal
- ghcup -c install 8.6.5
- ghcup -c set 8.6.5
- ghc --version
- cabal --version
- cabal update
- "cabal user-config update -a 'tests: True'"


# Build the package, its tests, and its docs and run the tests
script:
- cabal build
- cabal test
