name:                projectEuler
version:             0.1.0.0
github:              "githubuser/projectEuler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: app

executables:
  projectEuler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projectEuler

tests:
  projectEuler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - projectEuler
